name: petsc_env
channels:
  - mrossi
  - conda-forge

dependencies:
  - python=3.12
  - pyvista
  - pyevtk
  - numpy
  - matplotlib
  - sympy
  - scipy
  - meshio
  - meshpy
  - colorama
  - petsc4py
  - tqdm
  - pip
  - pip:
    - gmsh
