name: dsc_env
channels:
  - mrossi
  - conda-forge

dependencies:
  - python=3.9
  - pyvista
  - pyevtk
  - numpy=2.0.2
  - matplotlib
  - sympy
  - scipy
  - meshio
  - meshpy
  - colorama
  - tqdm
  - pip
  - pip:
    - gmsh
